### PR TITLE
fix building on iOS

### LINKED ISSUE #129: Linking Error: Undefined Symbols Due to Missing AVFoundation Framework, Breaking iOS Build
running `make run` command to build for ios target fails due to linking error. probably related to  #128.

❌ Error Message:

~~~make
Undefined symbols for architecture arm64:
  "_AVAudioSessionCategoryAmbient", referenced from:
      _main_rs in libmobile.a[2](mobile-c637714a32ea4ff4.0s3a5vvu0qtad299j2alsro0q.rcgu.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
~~~

✅  Fix:

Link the AVFoundation framework in Xcode:

1. Open the .xcodeproj file.
2. In the Project Navigator, select "mobile" project, under "Targets" select "mobile"
3. Go to the "Build Phases" tab and expand "Link Binary with Libraries."
4. Click the + button, search for "AVFoundation," and add AVFoundation.framework.
5. Ensure it's marked as "Required."
6. Clean the project (Shift + Command + K) and rebuild.

### PR DESCRIPTION
**Pull request by extrawurst**
this fixes #129

* add AVFoundation.Framework
* adapt to bevy 0.16 [change](https://github.com/bevyengine/bevy/pull/14780) in bevy_main macro for iOS

### CODE REVIEW

File: mobile/src/lib.rs [hunk 1]
```diff
@@ -3,7 +3,11 @@ use bevy::window::WindowMode;
 use bevy::winit::WinitSettings;
 use bevy_game::GamePlugin; // ToDo: Replace bevy_game with your new crate name.
 
-#[bevy_main]
```
Comment (NiklasEi) [inline mobile/src/lib.rs:6]: Do we not still need this for Android?

Comment (extrawurst) [reply mobile/src/lib.rs:6]: Damn yeah we do

Comment (extrawurst) [reply mobile/src/lib.rs:6]: added it back, as it is a no-op on iOS
